#!/usr/bin/env python

import itertools
import re
import sys
import dot

default_task = "do_build"

try:
    dotfile = sys.argv[1]
    target = sys.argv[2]
except IndexError:
    sys.exit("Usage: dot-to-recipes.py DOTFILE TARGET")


# Get dependency information
depends = dot.parse_depends(dotfile)

# Flatten into a list of recipes
depend_list = dot.get_all_depends(depends, '%s.%s' % (target, default_task))

recipes = list(node[0] for node in depend_list if node[1] == 'do_populate_sysroot')
for recipe in recipes:
    print(recipe)
